### ISSUE TITLE
Ammo

### ISSUE THREAD

**Issue by rafaelm71** [HumanTree92/esx_extraitems#17]
**Describe the Bug | A Clear & Concise Description of Bug**
When I use the weapon clip in the pistol it works but when I use other weapons like the sns pistol, it doesnt recharge it, it only works for few weapons.

**Questions**
Have you looked through the Closed Topics?: 
yes
Have you looked through the Wiki?: 
yes
What Version of es_extended are you using?: 
es extended v1
Are you using a Pre-Installed ESX?: 

Are you using Essentialmode?: 
no
Are you using OneSync?: 
yes
Linux or Windows?: 
Windoes

**Comment by YInfeRnal** [comment]
this not working.. he say I think I did some shit, closing for now.
and close
i check and do that but not working
100% not work

**Comment by HumanTree92** [comment]
Should be fixed in https://github.com/HumanTree92/esx_extraitems/commit/bd806408a6b51894480aca78ec667b9830d099b6

**Comment by SkinnyDragonCodes** [comment]
This is still not working for me. I am on the correct version etc. Still not retaining the ammo count on relog or restart.

**Comment by HumanTree92** [comment]
If it's not working then there is some wrong with ur es_extended.

**Comment by SkinnyDragonCodes** [comment]
I have worked out what it is, If you have two pistols and you stock up on ammo, lets say 250 bullets, obviously the guns share the same ammo but when I leave the game and join back it will decrease back down to 145 or 45. I don't know if this is fixable.. It works when you have one pistol but does this when you have more than one type of pistol/ weapon class..

**Comment by Valkyrionas** [comment]
Hello there sorry for bothering you again on another topic HumanTree92, but I have (or had) the issue also, I'm using es_extended 1.2 and had the old esx_extraitems used, so there was the bug on missing the ammo from logoff to the next login on Pistols/MPs and Rifles. I have updated the old to your newer version here and nearly fixed everything with one Exception... the normal Pistol doesnt seem to get the loadout from the database loeaded in ingame if you connect. As Example, I shoot out all Ammo of the Pistol and take a bigbox (100 ammo) those are filled in, I Log off and log in and it is still missing ammo in the pistol... but all other weapons are fixed now (indeed in the database is written 100 ammo but ingame it is only filled on 12/30)... you may have a clue why just the pistol is not able to take the correct loadout of the database, has it somethin to do with es_extended or is it related to another issue on a other script ? for the shops im using esx_supermarket (which also works fine for the shops, just had to adjust it in the ressource.lua / fxmanifest as dependency - just for those who use also esx_supermarket). Would be cool if anyone could provide a idea on the normal "pistol-issue"

best regards...
